-- 插入示例招标项目数据
INSERT INTO tender_projects (
    project_id, title, description, bidder, agency, location, category,
    fund_source, project_scope, qualification, registration_start_time,
    registration_end_time, document_start_time, document_end_time,
    clarification_end_time, bid_deadline, estimated_amount,
    supervisor_name, supervisor_phone, contact_name, contact_phone,
    contact_email, contact_address, department, position,
    publish_time, create_time, is_active
) VALUES (
    'YZ20250814000015',
    '中粮油脂西部区川渝工厂药剂采购项目竞价采购(集中)公告(0001标段中粮油脂西部区川渝工厂药剂采购项目)',
    '化验室药剂正己烷采购项目',
    '中粮油脂(广元)有限公司',
    '未获取到代理单位',
    '四川-广元',
    '招标公告',
    '自筹资金',
    '化验室试剂正己烷',
    '--',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '2025-08-19 12:00:00',
    '-',
    '王祺',
    '139****6124',
    '赵丹',
    '186****5220',
    'zhaodan@cofco.com',
    '--',
    '采购部',
    '采购专员',
    '2025-01-19 10:00:00',
    '2025-01-19 10:00:00',
    true
);
